### ISSUE TITLE
Friendly ping from dry-python/returns

### ISSUE THREAD

**Issue by sobolevn** [mysticfall/alleycat-reactive#1]
Hi @mysticfall! 

Very impressive work on ROP! I have looked through the code and it looks amazing!
I will totally try this out.

I would love to share some news about `returns`: 
1. (I am not sure if you have seen this or not, but, anyways) We are working on HKT support: https://github.com/dry-python/returns/tree/master/returns/interfaces So developers would be able to write their own monads and reuse all our features with builtin type-safety. 
2. There would be a lot of breaking changes in a new version (sadly, but HKT requires it)
3. I would love to invite you to our chat in telegram, where we discuss a lot of `dry-python` related stuff: https://t.me/drypython

Best regards,
Nikita Sobolev

**Comment by mysticfall** [comment]
@sobolevn I'm very glad to see you here and I can't wait to hear opinions from a seasoned Python/FP programmer like you. 

I'm still not confident as to the feasibility of my idea behind this project as I've yet to write anything serious with it (which I'm planning to do very soon). So, it'd be much helpful to me if someone with your knowledge and skills could provide an insight.

Although I created this project as a complementary library _for_ RxPy, it was made _with_ Returns, so I'm naturally much interested to see where your project is headed. And I wouldn't mind breaking changes at all, as long as they are needed to make it even better.

Thanks much for the kind words, and also for the invitation! :)

P. S.: I will close this issue for housekeeping, but please feel free to add comments if needed.
